# syntax=docker/dockerfile:1
FROM python:alpine

COPY AA_Registry.py AA_Registry.py
COPY RegistryParameters.json RegistryParameters.json
COPY deleteMaps.py /db/deleteMaps.py
COPY initDatabase.py /db/initDatabase.py
