services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'againstall'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'clara'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'sd2022'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'sd2022'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql:rw
      - mysql_config:/etc/mysql:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    restart: always
    ports: 
        - 8080:8080

# Names our volume
volumes:
  mysql:
  mysql_config: